version: 'v3'
services:
  eureka:
    build: ./eureka-server
    ports:
      - 8761:8761
  user-db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE: user

    secrets:
      - db_user
      - db_password
  user-service:
    build:
      context: .
      dockerfile: ./user-manager/Dockerfile

    environment:
      DB_HOST: user-db
      DB_PORT: 3306
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      EUREKA_HOST: eureka

    secrets:
      - db_user
      - db_password
  product-db:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE: product

    secrets:
      - db_user
      - db_password
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

secrets:
  db_user:
    file: ./secrets/db-user.txt
  db_password:
    file: ./secrets/db-password.txt