debug: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - POST
              - GET
              - OPTIONS
            allowed-headers: '*'
      routes:
        - id: user-service
          uri: lb://user-manager
          predicates:
            - Path=/**
            - Method=POST,GET
        - id: preflight
          uri: no://op
          predicates:
            - Path=/**
            - Method=OPTIONS
