debug: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - POST
              - GET
              - DELETE
              - OPTIONS
            allowed-headers: '*'
      routes:
        - id: user-service
          uri: lb://user-manager
          predicates:
            - Path=/auth/**
            - Method=POST,GET
        - id: product-service
          uri: lb://product-manager
          predicates:
            - Path=/products/**
            - Method=GET
        - id: picture-service
          uri: lb://product-manager
          predicates:
            - Path=/pictures/**
            - Method=GET
        - id: cart-service
          uri: lb://shopping-cart
          predicates:
            - Path=/cart/**
            - Method=GET,POST,DELETE
        - id: preflight
          uri: no://op
          predicates:
            - Path=/**
            - Method=OPTIONS
