eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${PORT:0}

spring:
  application:
    name: "shopping-cart"
  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/cart"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: create-drop

shop:
  auth:
    jwt:
      private-key:
        algorithm: rsa
        location: ${PRIVATE_KEY_FILE}
      public-key:
        algorithm: rsa
        location: ${PUBLIC_KEY_FILE}