spring:
  application:
    name: "user-manager"
  datasource:
    url: "jdbc:mariadb://${DB_HOST: localhost}:${DB_PORT: 3306}/user"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: create-drop

user-manager:
  auth:
    jwt:
      private-key:
        algorithm: rsa
        location: keys/private_key.pem
      public-key:
        algorithm: rsa
        location: keys/public_key.pem
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka

