server:
  port: ${PORT:0}

spring:
  application:
    name: "user-manager"
  datasource:
    url: "jdbc:mariadb://${DB_HOST: localhost}:${DB_PORT: 3306}/user"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: create-drop

shop:
  auth:
    jwt:
      private-key:
        algorithm: rsa
        location: ${PRIVATE_KEY_FILE}
      public-key:
        algorithm: rsa
        location: ${PUBLIC_KEY_FILE}
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: "http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka"

