server:
  port: ${PORT:8081}

spring:
  application:
    name: product-manager
  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/product"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

shop:
  auth:
    jwt:
      private-key:
        algorithm: rsa
        location: ${PRIVATE_KEY_FILE}
      public-key:
        algorithm: rsa
        location: ${PUBLIC_KEY_FILE}